
# Constants
CONTEXT_LENGTH = 64
STRIDE = 8
VOCAB_SIZE = 50257  # GPT-2 vocabulary size
NUM_EXPERTS = 8
HIDDEN_DIM = 64 
NUM_HEADS = 4  
NUM_LAYERS = 4
DATA_FRACTION = 0.1
BATCH_SIZE = 8
TOTAL_EPOCHS = 10