
# Constants
CONTEXT_LENGTH = 128
STRIDE = 32
VOCAB_SIZE = 50257  # GPT-2 vocabulary size
NUM_EXPERTS = 2
HIDDEN_DIM = 16 
NUM_HEADS = 2  
NUM_LAYERS = 2
DATA_FRACTION = 0.15
BATCH_SIZE = 8
TOTAL_EPOCHS = 100
LEARNED_WEIGHTS_WEIGHTAGE = 0.6
TOKEN_ASSIGNMENT_WEIGHTAGE = 1.0 - LEARNED_WEIGHTS_WEIGHTAGE 
DIVERSITY_LOSS_WEIGHTAGE = 0.2
BALANCE_LOSS_WEIGHTAGE = 0.1
ROUTING_LOSS_WEIGHTAGE = BALANCE_LOSS_WEIGHTAGE
TASK_LOSS_WEIGHTAGE = 1.0 - (DIVERSITY_LOSS_WEIGHTAGE+BALANCE_LOSS_WEIGHTAGE)